### ISSUE TITLE
Refactor exports and imports of page components

### ISSUE THREAD

**Issue by rcamach7** [lugenx/ecohabit#102]
1)  Create a `index.js` file inside of client/src/pages
2) Export all page components that exist in the sub folders inside this newly created file. Example: 

```js
// index.js
export { default as CarbonFootprint } from "./CarbonFootprint/CarbonFootprint.js"
... // do this for all pages (only primary component)
```
3) Inside client/src/components/Routes.js group all imports using the default export we just created that are coming from client/src/pages

```js
// instead of 
import Homepage from "../pages/Homepage/Homepage";
import ErrorPage from "../pages/Error/ErrorPage";

// do this (these are just two, you would add all the rest)
import { Homepage, ErrorPage } from  "../pages";
```

4) Run `npm start` and make sure you don't get any errors

**Comment by xinyi-dev** [comment]
hi! could I try this out?

**Comment by lugenx** [comment]
hi, sure. assigned. go ahead.
