### ISSUE TITLE
Remove wrapping div element from App.js

### ISSUE THREAD

**Issue by rcamach7** [lugenx/ecohabit#123]
Component `Routes` is wrapped by a div that isn't needed. Remove it and have `App` component simply return just the `Routes` component.

* `client/src/App.js`
* make sure you have prettier installed on your code editor
* run `npm start` once inside of the `client` directory to check for any errors

**Comment by Manoharvuradi** [comment]
Hey @rcamach7 I would like to work on this issue. But I would like to know what's the problem having if it is wrapped by a `<div>`?

**Comment by rcamach7** [comment]
> Hey @rcamach7 I would like to work on this issue. But I would like to know what's the problem having if it is wrapped by a `<div>`?

Hello @Manoharvuradi! Right now it doesn't serve a purpose, so it's just an extra element wrapped around the entire application. It's more so for good practice on keeping the codebase clean and uncluttered
