### ISSUE TITLE
Add Figma file link to README

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#128]
As part of the documentation, it would be helpful to have a link to the Figma file in the README file so that contributors can view the design. Please make sure that the file is view-only accessible.

Please include the link in the README file under the section "## Design" after the "## Project Description" section and before the "## Tech Stack" section in the following format:
```markdown
## Design

The design for this project can be viewed in the [Figma file](<link to file>)
```

**Comment by HeroicSam** [comment]
GoldenBoy here!

**Comment by lugenx** [comment]
Assigned, thank you.

**Comment by HeroicSam** [comment]
Any place within the readme you want me to add this to in particular? Was thinking under Roadmap but I could also see it having its own section. Happy to defer to your best judgment.

**Comment by lugenx** [comment]
> Any place within the readme you want me to add this to in particular? Was thinking under Roadmap but I could also see it having its own section. Happy to defer to your best judgment.

please read the body of the issue for the exact location.

**Comment by lugenx** [comment]
@HeroicSam, any update on this?
