### ISSUE TITLE
Replicate Bottom Navigation From MUI Docs

### ISSUE THREAD

**Issue by rcamach7** [lugenx/ecohabit#129]
You will be pulling the example in the MUI docs, and directly replicating it. We will update all the links, images, and texts later. 

* inside `client/src/components` create a folder called `BottomNavigation` then create a file called `BottomNavigation.js` 
* visit [this link](https://mui.com/material-ui/react-bottom-navigation/#bottom-navigation-with-no-label) and copy the demo labeled as "Bottom navigation with no label" as is. Make sure it's the JS version. 
* past this into `client/src/components/BottomNavigation/BottomNavigation.js`
* organize and group imports

instead of
```js
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
```
group them and do this
```js
import { AppBar, Box, Toolbar, etc } from '@mui/material';
```

I will be available incase you have any more questions or you come across any issues

**Comment by dignit28** [comment]
Hello, I would like to work on this issue.

**Comment by rcamach7** [comment]
> Hello, I would like to work on this issue.

Assigned!
