### ISSUE TITLE
Create Demo Page For Testing

### ISSUE THREAD

**Issue by rcamach7** [lugenx/ecohabit#130]
You will be adding a demo page to test new components being built. It will be empty for now. 

* inside `client/src/pages` create a folder called `Demo` then create a file called `Demo.js` 
* Create a empty component inside that file and export it
* export this component under `client/src/pages/index.js` as well. Follow the same format as you see inside that file. 
* inside `client/src/components/Routes.js` import the Demo component, and create a new route for it. Follow the same pattern as you see other routes being defined.
* run `npm` start and make everything runs without errors

I will be available throughout incase you have any more questions or you come across any issues

**Comment by SumeetMaurya** [comment]
can you assign me this issue

**Comment by rcamach7** [comment]
> can you assign me this issue

Yes, thank you!

**Comment by lugenx** [comment]
@SumeetMaurya , could you please provide an update on this?

**Comment by lugenx** [comment]
Since there is no response from the potential contributor, I will remove this assignment and make this issue available for others to get assigned.

**Comment by rafaover** [comment]
!assign

**Comment by rafaover** [comment]
Just to make sure. Do you want to modify the `client/src/index.js` or do you want to CREATE a new file `Index.js` inside pages?

**Comment by lugenx** [comment]
Assigned @rafaover  thank you, 

to answer your question:

i think you should create a folder inside `client/src/pages` called Demo, then create a file called Demo.js

I recommend you to read the body of the issue. Feel free to ask questions if something is still not clear after reading.
