### ISSUE TITLE
Replicate 'Card' From MUI Docs

### ISSUE THREAD

**Issue by rcamach7** [lugenx/ecohabit#131]
You will be pulling the example in the MUI docs, and directly replicating it here. We will update all the links, images, and texts later. 

* inside `client/src/components` create a folder called `HabitCard` then create a file called `HabitCard.js` inside 
* visit [this link](https://mui.com/material-ui/react-card/#media) and copy the demo labeled as "Media" as is. Make sure it's the JS version
* past this into `client/src/components/HabitCard/HabitCard.js`
* organize and group imports like so:

instead of
```js
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
```
group them and do this
```js
import { AppBar, Box, Toolbar, etc } from '@mui/material';
```
* run `npm start` to check for any errors

I will be available throughout incase you have any more questions or you come across any issues

**Comment by SumeetMaurya** [comment]
can I work on this

**Comment by rcamach7** [comment]
> can I work on this

I assigned you another issue, after that's done, if this one is still open, sure!

**Comment by markhallak** [comment]
Can I work on this?

**Comment by rcamach7** [comment]
> Can I work on this?

Yes, thank you!
