### ISSUE TITLE
Create a login and a sign-up page

### ISSUE THREAD

**Issue by mannan0819** [lugenx/ecohabit#135]
On the client create a page where user can fill out a form to register. 
Connect it to the backend route for user register

**Comment by lugenx** [comment]
@Lyndsayfutrell here are the Figma designs of login and sign-up pages: https://www.figma.com/file/huzjiocev2qJhtr2ntusf6/EcoHabit?node-id=5%3A3

**Comment by lugenx** [comment]
I will have to remove this assignment since there has been no update for a month. It is available now if anybody else wants to work on this.

**Comment by Dinesh-Khanal** [comment]
assign this for me, I'll do.
