### ISSUE TITLE
Add error handlers to updateHabit and deleteHabit controllers

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#144]
The `updateHabit` and `deleteHabit` functions in our `habitController.js` file are missing error handlers, which could lead to unexpected behaviors and data integrity issues. We should add appropriate error handling to ensure that the application behaves as expected even in the event of errors.

Please wrap the code with try/catch block.

You can check `userController.js` as an example.

**Comment by tsimian** [comment]
May I handle this issue while my other issue waits for the review of #142?

**Comment by lugenx** [comment]
assigned! please go ahead.
