### ISSUE TITLE
Fix routing on the mobile menu

### ISSUE THREAD

**Issue by tsimian** [lugenx/ecohabit#147]
The routing on the mobile menu seems to not be working properly, though it is working on desktop. There should be a link to the pages added to the MenuItem found on line 94 of ResponsiveAppBar.js.

This can be fixed by copying lines 125-126 on the Button and pasting them inside the MenuItem.

**Comment by Dinesh-Khanal** [comment]
Can you assign me this issue?

**Comment by lugenx** [comment]
Assigned. Thanks.
