### ISSUE TITLE
Implement a Basic User Profile Page with Material UI and Link it to the Homepage

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#148]
We need to create a simple user profile page using the [Material UI](https://mui.com/). The page should have a name placeholder and an editable zip code field. We want to link this profile page to our homepage by including a profile link in the navigation menu.

This page will allow users to view and edit their basic information and will be improved with additional details in the future.

**Comment by tsimian** [comment]
May I be assigned this issue?

**Comment by lugenx** [comment]
Assigned. 👍
