### ISSUE TITLE
Fix error for missing unique keys on the buttons in HabitCard

### ISSUE THREAD

**Issue by tsimian** [lugenx/ecohabit#153]
The error is occurring with the answerOptions buttons in the card on lines 32-36. This can be fixed by adding the index as a parameter to the callback function on line 32. Then add a key prop to the button on line 33 with the index as the value.

**Comment by JonGeorge** [comment]
May I be assigned to this issue?

**Comment by lugenx** [comment]
Assigned. Thank you 👍

**Comment by JonGeorge** [comment]
I submitted #158 for this issue.
