### ISSUE TITLE
Update .env.example file in Client directory

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#154]
As you can see, the following environment variable used in the Homepage component (`ecohabit/client/src/pages/Homepage.js`)
  ```env
  const API_URL = process.env.REACT_APP_API_URL;
  const TOKEN = process.env.REACT_APP_TOKEN;
  ```

Currently, in .env.example file includes only `BASE_URL=http://localhost:3001`  

Please change the variable name to `REACT_APP_API_URL` and add the `REACT_APP_TOKEN` variable to match the `Homepage.js` component.

Changed `.env.example` file should look as below:

 ```env
REACT_APP_API_URL=http://localhost:3001
REACT_APP_TOKEN=
```

**Comment by JonGeorge** [comment]
Can I be assigned to this issue?

**Comment by lugenx** [comment]
Assigned. Thanks 👍

**Comment by gjuliao** [comment]
Is the issue covered? If not you can assign me to get it done.  Best,

**Comment by JonGeorge** [comment]
I submitted a PR already. See https://github.com/lugenx/ecohabit/pull/157
