### ISSUE TITLE
Add an Error Handling Middleware Function to the Index file

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#160]
We need to add an error handling middleware function to catch and respond to unexpected errors.

Here are the steps to add the middleware function:

1. Create an error handling middleware function inside the `server/src/middleware` folder that catches and responds to unexpected errors.
2. Import and use the error handling middleware function at the end of the index.js file.
3. Test the error handling middleware function by intentionally triggering errors.

**Comment by AbhiramKrishnaM** [comment]
May i be assigned to this task

**Comment by lugenx** [comment]
Assigned, thanks.

**Comment by AbhiramKrishnaM** [comment]
Hey, added the unexpected error module.  I have also added a error test route, which basically throws an error.

**Comment by AbhiramKrishnaM** [comment]
hey updated the error module, can you check please

**Comment by AbhiramKrishnaM** [comment]
@lugenx hey  did you check the pr ?

**Comment by lugenx** [comment]
this issue is available if someone wants to work on this.

**Comment by AbhiramKrishnaM** [comment]
its fixed no ? i dont understand

**Comment by Dinesh-Khanal** [comment]
I will work on this issue, can you assign it for me?

**Comment by lugenx** [comment]
@Dinesh-Khanal assigned, thank you.
