### ISSUE TITLE
Return appropriate HTTP response status codes

### ISSUE THREAD

**Issue by tsimian** [lugenx/ecohabit#162]
It seems we are not returning the appropriate status codes in the back end. Such as in each controller we are returning ‘200 OK’ when creating habits/answers instead of ‘201 Created’.  In auth.js we are returning a ‘403 Forbidden’ if there is no token instead of ‘401 Unauthorized’, and instead of sending "Access Denied" we could send "Not Authorized".

Also feel free to look for other incorrect status codes and use this [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status](url) as a reference.

**Comment by JonGeorge** [comment]
I have a couple other things on my plate, but would be able to get this done within the next week or so. If you're ok with that time frame, may I be assigned to this issue @tsimian?

**Comment by tsimian** [comment]
I think that sounds fine, what do you think @lugenx?

**Comment by lugenx** [comment]
@JonGeorge thank you for actively contributing. There are already two open pull requests you are working on, and please check back once they are done, if this is open until then, we can definitely assign it to you. If not, we have much more issues coming.

**Comment by AbhiramKrishnaM** [comment]
May i be assigned to this task

**Comment by DenuwanLiyanage** [comment]
If no one is assigned to this, I can look into the issue

**Comment by lugenx** [comment]
thank you all for your interest, since @AbhiramKrishnaM also has another PR open, I will assign this issue to @DenuwanLiyanage

**Comment by DenuwanLiyanage** [comment]
Thank you I will start working on this.

**Comment by DenuwanLiyanage** [comment]
Hi,

In answerController.js you are sending a 404 status if mongoose type validation fails. 
```
if (!mongoose.Types.ObjectId.isValid(id)) {
    return res.status(404).json({ error: "answer not found, invalid request" });
  }
```

I'm suggesting sending a 400 status like the below,
```
if (!mongoose.Types.ObjectId.isValid(id)) {
    return res.status(400).json({ error: "Bad Request" });
  }
```
I'm hoping to find an answer here.

**Comment by DenuwanLiyanage** [comment]
Thank you for your reply @tsimian. I will make those changes.

**Comment by DenuwanLiyanage** [comment]
You are welcome and thank you for the support.
