### ISSUE TITLE
Fix formatting in README file

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#169]
In the first bullet of the "How to run" section, 'git clone https://github.com/lugenx/ecohabit.git' is shown in a single quotation mark. To make this like other commands in the document, single quotation marks should be changed with backticks. should look like this:
`git clone https://github.com/lugenx/ecohabit.git`

**Comment by shyamtawli** [comment]
Can I work on it?

**Comment by lugenx** [comment]
I see two pull requests for this issue; since @shyamtawli asked for an assignment here first, I will have to close one that @yashkhandelwal123 opened. To avoid this kind of conflict, please wait to get assigned to the issue before working on it. Thank you both for your interest in contributing to the project.

**Comment by shyamtawli** [comment]
Thanks @lugenx I will get first assigned than work on it in future.
