### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [lugenx/ecohabit#173]
I would like to work on the README.md file of this repo and make some minor changes like
+ Restructuring content for a better appeal
+ Adding badges for tech tack and discord for a cool effect

I would like to be assigned to the issue if approved!

**Comment by lugenx** [comment]
Thank you @the-amazing-atharva, Could you please explain a little bit more specifically what issues you found in the README file and how you think you can improve it?

**Comment by the-amazing-atharva** [comment]
+ Improved the look of some links
+ Added these badges

Thoughts??
![image](https://user-images.githubusercontent.com/121221252/225203216-7c69bfd0-8f38-4750-8020-71611700edf7.png)

**Comment by lugenx** [comment]
i suggest keeping it simple for now, but you can make each tech linkable to their documentation, not sure if it's possible to open links in new tabs with markdown, if not, opening on the same tab is also fine. 

let me know if you would like to do it, i can assign this to you.

**Comment by the-amazing-atharva** [comment]
Yeah I can link the badges to the documentation, will make the changes soon!

**Comment by lugenx** [comment]
so what I meant that, we don't need to use badges, let's keep the formatting same, just make them link to documentations. 
assigned this to you. thank you.

**Comment by the-amazing-atharva** [comment]
Linked a PR for the same
