### ISSUE TITLE
Add error handling to answerController

### ISSUE THREAD

**Issue by tsimian** [lugenx/ecohabit#174]
The `getAnswer`, `updateAnswer`, and `deleteAnswer` functions in `answerController.js` are missing error handlers. This could cause unexpected behaviors. Please implement this error handling by wrapping the  code in each function in a try/catch block.

You can use `habitController.js` as an example.

**Comment by codepley** [comment]
Hey, I would like to work on this issue.

**Comment by tsimian** [comment]
Assigned, thank you @codepley
