### ISSUE TITLE
Integrate frontend with backend for login and registration

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#175]
Integrate the login and registration pages with the already implemented backend authentication system. Update the pages to send requests to the appropriate backend routes and handle responses from the server.

**Comment by jchen396** [comment]
Hi, I would like to be assigned to contribute to this issue if possible.

**Comment by lugenx** [comment]
Thank you for your interest. This issue is already in progress. See if you can find other unassigned issues, or you can watch for upcoming issues.
