### ISSUE TITLE
Desktop Login Page Not Matching Figma Design and Screen Fit

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#181]
### This is how it currently looks:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8403023/232639812-699f1012-3250-4519-b558-3d0d5a6fbbb3.png">

### The page should look exactly like in the link below:
https://www.figma.com/file/huzjiocev2qJhtr2ntusf6/EcoHabit?node-id=5%3A3&t=DDvocL56yYimKoQu-1

**Comment by aryan-debug** [comment]
So, you want to get rid of the header?

**Comment by aryan-debug** [comment]
![image](https://user-images.githubusercontent.com/52334622/232718373-c7bff2fd-b694-4de0-a28d-7be53b1a14e8.png)
This is where I am at right now

**Comment by lugenx** [comment]
hi @aryan-debug , the intention is not to get rid of the header, this issue is about matching the look of the current login page with the figma design in the link. It should match exactly with all the sizes and fit the screen correctly while staying within the standards of the material UI. If you think this is something that you can deliver, I can assign this issue to you. Please let me know.

**Comment by aryan-debug** [comment]
Yes, I can do this. I am not sure why you closed the pull request since I clearly mentioned the issue I was working on.

**Comment by lugenx** [comment]
thank you, @aryan-debug, I assigned this task to you, please go ahead. please read the comment I made in the pr for the reasons why it's closed.

**Comment by aryan-debug** [comment]
@lugenx Let me know if you want me to change anything.
![image](https://user-images.githubusercontent.com/52334622/233776408-7dfcbb07-acc2-4cf1-8a77-b408a3977d3b.png)

**Comment by lugenx** [comment]
@aryan-debug , from the image, it looks good overall, but could you make a pull request for closer review.
