### ISSUE TITLE
Replace 'Lorem ipsum' placeholder text on the login page

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#183]
The current placeholder text, "Lorem ipsum dolor sit amet, consectetur," should be replaced with more relevant content.

Please provide your suggested text below, and give a thumbs up if you like someone else's submission. The person with the most likes will be assigned the task.

**Comment by ijklmopffs** [comment]
Hello, could you provide more details on this. I'm struggling to see the placeholder text you're referring to

**Comment by lugenx** [comment]
> Hello, could you provide more details on this. I'm struggling to see the placeholder text you're referring to

sure @ijklmopffs, please see the below screenshot to find out the placeholder text I was talking about:

![image](https://user-images.githubusercontent.com/8403023/233200222-376cfb70-fe01-499b-8bce-b48057bcf67a.png)

**Comment by ijklmopffs** [comment]
Alright. I'd work on it.

**Comment by lugenx** [comment]
thank you, @ijklmopffs, could you please post below what sentence would you use for the login page?

**Comment by victorchrollo14** [comment]
hey @lugenx is anyone working on this issue? 
I would like to add it, Which one do you think makes sense.
"Nurturing eco-friendly habits together."
"Empowering environmental consciousness globally."
"Building a greener tomorrow, today."
"Inspiring eco-conscious living choices."
"Transforming habits for our planet."
"Championing eco-friendly lifestyles."
"Creating awareness through sustainable actions."
"Unleashing the power of green habits."
"Making sustainability a way of life."
"Embrace the ecohabit revolution."

**Comment by victorchrollo14** [comment]
"Building a greener tomorrow, today." I think this is good.

**Comment by lugenx** [comment]
Thank you @victorchrollo14 , for these options. There are the ones I liked more from your list:

- "Inspiring eco-conscious living choices."
- "Transforming habits for our planet."
- "Creating awareness through sustainable actions."
- "Unleashing the power of green habits."
- "Making sustainability a way of life."

I would like to see what others think?

**Comment by tsimian** [comment]
Perhaps modify the 3rd one to "_Spreading_ awareness through sustainable actions"? Or "_Plan_ a greener tomorrow, today".

**Comment by victorchrollo14** [comment]
What should we go with then, "Spreading awareness through sustainable actions". This one seems nice, if everyone agrees on this one I'll add it up.
