### ISSUE TITLE
Implement email and password validation with validator.js

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#185]
Enhance the sign-up process by validating the email and password formats users enter by installing and using validator.js

Here are the steps:

1. Install validator.js as a dependency.
2. Add email validation to ensure it meets the standard format (e.g., user@example.com).
3. Add password validation to ensure it meets our desired criteria (e.g., minimum length, presence of numbers, and special characters).
4. Display appropriate error messages if the entered email or password doesn't meet the requirements.

**Comment by aryan-debug** [comment]
May I work on this issue?

**Comment by lugenx** [comment]
@aryan-debug thank you for your help, because you have already another issue assigned and it's in progress, let's wait to get that merged. if this issue is not assigned to anybody else until then, I will assign this to you.

**Comment by vishwaszadte** [comment]
hey, can I work on this?

**Comment by vishwaszadte** [comment]
@lugenx what exactly is the desired criteria for a password in this case?

**Comment by lugenx** [comment]
Assigned @vishwaszadte 👍 

Also, thank you for the recommendation, I wasn't aware of that just checked, and yes, it's a great idea, let's use it. But let's modify the options and make upper and lowercase optional. let's change `minLowercase` and `minUppercase` to 0.
```js
minLowercase: 0, 
minUppercase: 0
```
