### ISSUE TITLE
Improve UI/UX on the Locations page

### ISSUE THREAD

**Issue by tsimian** [lugenx/ecohabit#193]
### UI: 
- The form and the data returned in `Recycle.js` should be centered on the page.
- The `LocationCard` should not be so wide.

### UX:
- We should add a loader or spinner while the data is being fetched. MUI has built in components for this to make it much easier. We could implement the spinner `CircularProgress` by first importing it into `Recycle.js`, then create a variable using the state hook to check if `isLoading` is true or false.

**Comment by victorchrollo14** [comment]
Hey @tsimian . I'll start working on this issue.

**Comment by tsimian** [comment]
Assigned @victorchrollo14, good luck!
