### ISSUE TITLE
Display BottomNavigationBar on mobile screens

### ISSUE THREAD

**Issue by tsimian** [lugenx/ecohabit#194]
Start by adding the `BottomNavigationBar` component **after** the closing main tag in `MainLayout.js`. Then in `BottomNavigationBar.js` setting the breakpoint so that the display is set to "flex" on _xs_ screens and set to "none" on _md_ screens. (You can see how this is done in `ResponsiveAppBar.js`) Make sure the component is fixed to the bottom of the screen.

We could also change the icons displayed in the `BottomNavigationBar` component. Currently the values are 'Recents', 'Favorites', 'Nearby', and 'Folder'. For now lets change them to 'Home', 'Locations', 'Guides', and 'Profile'. This can be done by changing the _label_, _value_, and _icon_ of the BottomNavigationActions.

Feel free to select which icons you think would be best for each from [MUI's icon library](https://mui.com/material-ui/material-icons/) and import them into `BottomNavigationBar.js`

If you have any questions you can reach out on the Ecohabit discord server. (The link you can find in `README.md`)

**Comment by tarunsamanta2k20** [comment]
@tsimian is it looking good?

![image](https://github.com/lugenx/ecohabit/assets/55488549/e9313280-7347-4b9f-a799-d30906ccef68)

**Comment by tsimian** [comment]
> @tsimian is it looking good?
> 
> ![image](https://user-images.githubusercontent.com/55488549/239738146-e9313280-7347-4b9f-a799-d30906ccef68.png)

@tarunsamanta2k20 thank you for your help, but after discussing with @lugenx we may close this issue. If you are looking to make a first time contribution, please check out issue #193. If you are interested in it just comment and I can assign you!
