### ISSUE TITLE
Preserve User Input on Registration and Login Errors

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#196]
Currently, when a user encounters an error during registration or login, all input fields are cleared. This can be inconvenient as users have to re-enter all their information. 

To improve this, we'd like to:

1. Update the `handleSubmit` function in both components so that `clearData` is only called when the process is successful. This allows us to keep user input if an error occurs.

2. For security reasons, we should clear the 'password' and 'confirm password' fields in registration, and 'password' field in login even when an error occurs. Please incorporate this into the respective `handleSubmit` functions.

Upon completion, we should see:

- [ ] User input fields (except for password fields) are retained when an error occurs during registration.
- [ ] Password and 'confirm password' fields in registration, and 'password' field in login are always cleared after a submission attempt.

**Comment by kunal8411** [comment]
Hi @lugenx , Can you please assign this to me?
I will work on this issue. Thanks

**Comment by lugenx** [comment]
hi @kunal8411 , assigned, thank you 👍

**Comment by kunal8411** [comment]
Hi @lugenx I have created a PR for this issue, Please let me know if there is any enhancement I need to do, I will update PR accordingly. Thanks
