### ISSUE TITLE
Update 'How to run' section of README.md

### ISSUE THREAD

**Issue by tsimian** [lugenx/ecohabit#198]
We would like to update the README to help new contributors get the application running more easily.

In the ‘How to run’ section of README.md, underneath ‘Running Backend Node JS Application’ (please also fix the spelling mistake here), add this markdown:

```
- Create a _.env_ file at the root of the 'server' folder and copy the content from _.env.example_ into the new _.env_ file. 
```

**Comment by fernanda-freitas** [comment]
Hello, I went ahead and opened a pull request to fix this issue, do you want to assign it to me?

**Comment by victorchrollo14** [comment]
hey @tsimian adding the .env file part is fine, What about setting up mongodb atlas and replacing the URI in the .env file.
Should we not add that part.

**Comment by tsimian** [comment]
@fernanda-freitas assigned, and thank you! @victorchrollo14 we decided to leave the .env file the same for now, I can explain more in discord.
