### ISSUE TITLE
Add Field to Store User's Habits in User Model

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#211]
To track the habits selected by each individual user, we need to add a new field in the User model named habits. This field will hold an array of references (ObjectIds) to the Habit model.

Tasks to be done:

- Add a habits field to the User model, which will be an array of ObjectId references to the Habit model.
- Include a comment in the User model to clarify that the habits field represents habits chosen by the user and is distinct from the Habit model, which represents all available habits.

**Comment by vishwaszadte** [comment]
hey @lugenx I can pick this up

**Comment by lugenx** [comment]
Assigned 👍

**Comment by lugenx** [comment]
hi @vishwaszadte , any update on this?

**Comment by vishwaszadte** [comment]
Hey @lugenx my bad... getting started with it
