### ISSUE TITLE
Remove Unnecessary Folder Nesting in Components

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#217]
Currently, there are several folders in the 'components' directory, each holding only a single JavaScript file. This leads to unnecessary nesting and could make the project structure more complex than it needs to be. This also hampers easy navigation and file search within the codebase.

The following are the folders with only one JavaScript file:
- `BottomNavigationBar` folder includes only `BottomNavigationBar.js` file
- `Footer` folder includes only `Footer.js` file
- `MainLayout` folder includes only `MainLayout.js` file
- `ResponsiveAppBar` folder includes only `ResponsiveAppBar.js` file

We should refactor the project to eliminate these individual folders and place the component files directly into the 'components' directory. This will streamline our folder structure and improve project navigation.

**Acceptance Criteria:**

- Remove individual folders and move their respective `.js` files to the 'components' directory.
- Ensure all components are imported correctly where they are being used.
- Check and update any relative paths that may have changed as a result of this restructuring.
- No functionality should be impacted by this change.

Please note that additional clean-up work might be required after this restructuring, which will be addressed in separate issues as necessary. It's crucial to **perform this task carefully** to prevent any unintended side effects in the project.

**Comment by anmol111pal** [comment]
Hey @lugenx , I have fixed the issue. 
Kindly review & merge my PR.
Thanks
