### ISSUE TITLE
Update Mock API URL in `.env.example`

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#235]
We recently switched our mock API URL for the Earth911 service. The .env.example file still has the old URL, and it needs an update.

Current URL:
`EARTH911_BASE_URL=https://mockapi-earth911-ecohabit.up.railway.app`

New URL:
`EARTH911_BASE_URL=https://mockapi-earth911.ecohabit.org`

Tasks:

1. Locate the .env.example file in the `server` directory.
2. Update the EARTH911_BASE_URL with the new URL provided above.
3. Create a pull request with your changes. Make sure the only change is the URL update.

Tips:

- Ensure your local environment is set up according to our CONTRIBUTING guidelines.
- Please test locally to confirm the app functions as expected with the new URL.

**Comment by Sridharan2509** [comment]
Hi @lugenx , I have made the changes and raised a PR for the same. Please verify.

**Comment by Rohit-Yadavv** [comment]
Hi @lugenx , I have Updated Mock Api Url raised a PR for the same. Please verify.
