### ISSUE TITLE
Use Token from UserContext in Homepage Component

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#248]
Refactor the `Homepage` component to get the user token from `UserContext` instead of directly from `localStorage`.

**Steps:**
1. Replace `localStorage.getItem("token")` with the `token` from `useUserContext`.

    Remove:
    ```javascript
    const token = localStorage.getItem("token");
    ```
    Update importing userContext to look like this:
    ```javascript
    const { user, setUser, token } = useUserContext();
    ```

2. Ensure the app's functionality remains unchanged.

---
:warning: Before you start working on this issue, please comment below expressing your interest, and wait to be assigned. :warning:

**Comment by Devrishi-Dutta** [comment]
I want to do my first contribution, can you assign me this issue?

**Comment by lugenx** [comment]
assigned, thank you @Devrishi-Dutta . Let me know if you have any question.

**Comment by Devrishi-Dutta** [comment]
Am I supposed to do anything else after making the pull request? (in this issue )
