### ISSUE TITLE
Minor README Enhancements

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#253]
**Description:**
To ensure our README remains clear and consistent, I've identified a couple of minor improvements:

- [ ] Adjust the casing for "How to run" to "How to Run" to match the style of other headers.
- [ ] Correct the term "GIT" to "Git" in the "Contribute" section.

Thanks for your contribution!

**Comment by zedgamer9128** [comment]
I would like to try this.

**Comment by lugenx** [comment]
Assigned, please go ahead! :+1:
