### ISSUE TITLE
Cleanup client directory from boilerplate files and code

### ISSUE THREAD

**Issue by rcamach7** [lugenx/ecohabit#91]
We should remove these files that don't serve a purpose right now for us: 
- App.css
- App.test.js
- index.css 
- reportWebVitals function inside index.js
- reportWebVitals.js
- setUpTests.js

If anyone wants to take care of this I can review your changes, if not I can go ahead and do this.

 I will implement a CSS reset with MUI theme so above styling files are not needed.

**Comment by GrantMLambert** [comment]
I am working on this.
