### ISSUE TITLE
User Authentication setup

### ISSUE THREAD

**Issue by lugenx** [lugenx/ecohabit#96]

**Comment by AbhiBajpaishek** [comment]
@lugenx What's the scope of this ticket? I'm assuming, its scope involves creating a login endpoint using JWT?

**Comment by lugenx** [comment]
yes, exactly.

**Comment by lugenx** [comment]
maybe we should brake down pieces if you think it's to much work for a single issue. but i don't know how.

**Comment by AbhiBajpaishek** [comment]
> maybe we should brake down pieces if you think it's too much work for a single issue. but i don't know how.

No, creating a login endpoint in a single ticket sounds fair, though we need to decide on couple of things. 

1. What fields do we want to return in jwt body. 
2. We haven't established a connection with Mongo DB as yet, so do we need to add a ticket for that first?
3. Shall we create a registration endpoint first as that will put users' info in DB.

**Comment by AbhiBajpaishek** [comment]
> > maybe we should brake down pieces if you think it's too much work for a single issue. but i don't know how.
> 
> No, creating a login endpoint in a single ticket sounds fair, though we need to decide on couple of things.
> 
> 1. What fields do we want to return in jwt body.
> 2. We haven't established a connection with Mongo DB as yet, so do we need to add a ticket for that first?
> 3. Shall we create a registration endpoint first as that will put users' info in DB.

Just saw changes are merged for #95. Updated Questions:

- Shall we create a ticket to add OTP authentication for registration?
- MongoDB URI? 
- Where would we store JWT Secret
- What fields do we want to return in jwt body.

**Comment by lugenx** [comment]
1. i need to brainstorm on that
2. we already established connection to MongoDB, its in the runServer function in the index file.
3. i created an endpoint but it will be changed when we work on auth.

**Comment by lugenx** [comment]
there is actually another open pr #101 , at a quick glance it looks like some user auth stuff is handled, but i need to clone and check closely to see how we are going to proceed with that pr.
yeah, MongoDB URI will be stored in env file and added to railway.app as an env variable. i think we can do the same thing to jwt secret as well?

**Comment by AbhiBajpaishek** [comment]
> there is actually another open pr #101 , at a quick glance it looks like some user auth stuff is handled, but i need to clone and check closely to see how we are going to proceed with that pr. yeah, MongoDB URI will be stored in env file and added to railway.app as an env variable. i think we can do the same thing to jwt secret as well?

Sounds good, though IDK how railway app works, so how will we get URI from railway app?

**Comment by lugenx** [comment]
yeah, there is a section that holds environmental variables.
you are basically copy paste whatever is in your env file and it takes variables from there with the same exact variable (for ex. process.env.MONGO_URI)

**Comment by lugenx** [comment]
if anybody needs a uri for development purpuse, one can simply create a free db and put their own uri to the env file and use it.
